### ISSUE TITLE
Compilation error with vue-cli

### ISSUE THREAD

**Issue by kmaxat** [phoenixwong/vue2-timepicker#13]
ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue2-timepicker/src/vue-timepicker.vue
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/kmaxat/Development/vue-test/node_modules/vue2-timepicker/.babelrc" at 0, attempted to resolve relative to "/Users/kmaxat/Development/vue-test/node_modules/vue2-timepicker"
    at /Users/kmaxat/Development/vue-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/kmaxat/Development/vue-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/Users/kmaxat/Development/vue-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/Users/kmaxat/Development/vue-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/kmaxat/Development/vue-test/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/kmaxat/Development/vue-test/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/kmaxat/Development/vue-test/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/kmaxat/Development/vue-test/node_modules/babel-loader/lib/index.js:38:20)
    at Object.module.exports (/Users/kmaxat/Development/vue-test/node_modules/babel-loader/lib/index.js:133:12)
 @ ./~/vue2-timepicker/src/vue-timepicker.vue 8:18-108
 @ ./~/vue2-timepicker/index.js
 @ ./src/main.js

**Comment by phoenixwong** [comment]
Sorry for the long wait. The latest release [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0) has upgraded to support vue-cli now.

**Comment by phoenixwong** [comment]
Related to #15
