### ISSUE TITLE
Module build failed: Error: Couldn't find preset "es2015" relative to directory 

### ISSUE THREAD

**Issue by martinnaughton** [phoenixwong/vue2-timepicker#28]
Just installed vue-timepick and i got this error when i tried to use it in the component

`
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/node_modules/vue2-timepicker"
    at /node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/martin/git/dean-frontend/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (node_modules/babel-loader/lib/index.js:163:20)
`

I fixed the issue by installing this package. To fix it could be added as a dependency to the package.
`npm install  babel-preset-es2015 --save`

**Comment by Musmula** [comment]
In a Laravel project of mine I had a similar issue where I had to install the transform-runtime babel plugin and some other stuff, this command did it for me:

`yarn add babel-plugin-transform-runtime babel-preset-es2015 babel-preset-stage-2 --dev`

For npm this would look something like this: `npm install --save-dev babel-plugin-transform-runtime babel-preset-es2015 babel-preset-stage-2`

**Comment by StevteJin** [comment]
I also have this question

**Comment by StevteJin** [comment]
It's no useful for me:npm install babel-preset-es2015 --save

**Comment by migudonatien** [comment]
:npm install babel-preset-es2015 --save-dev work for me

**Comment by phoenixwong** [comment]
Closing this with the new release [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0) [#66]

**Comment by phoenixwong** [comment]
Related to #15
