### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Ash941114** [phoenixwong/vue2-timepicker#31]
ERROR in ./~/vue2-timepicker/src/vue-timepicker.vue
Module parse failed: F:\Working\node_modules\vue2-timepicker\src\vue-timepicker.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (F:\Working\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (F:\Working\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (F:\Working\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (F:\Working\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (F:\Working\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (F:\Working\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (F:\Working\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (F:\Working\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExpression (F:\Working\node_modules\acorn\dist\acorn.js:1573:21)
    at Parser.pp$1.parseStatement (F:\Working\node_modules\acorn\dist\acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (F:\Working\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (F:\Working\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (F:\Working\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (F:\Working\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (F:\Working\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (F:\Working\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (F:\Working\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at F:\Working\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (F:\Working\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at F:\Working\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
 @ ./~/vue2-timepicker/index.js 1:17-52

**Comment by Ash941114** [comment]
i have error "npm run build"

**Comment by morgan-schwertfeger** [comment]
Same error here.

**Comment by morgan-schwertfeger** [comment]
Ash941114 as a stop gap until a fix emerges I imported the src file and css code into my own component and serve it from my project folder.  It won't get updates, but hopefully temporary.

**Comment by Uninen** [comment]
Same error here also

**Comment by Uninen** [comment]
Answering to myself; my webpack configuration had `exclude: /node_modules/` line with `.vue` modules. Removing it solved the issue.

**Comment by jobelenus** [comment]
That didn't solve it for me, I have `{ test: /\.vue$/, loader: 'babel-loader'}` and still getting error

**Comment by jobelenus** [comment]
Derp, use `vue-loader`

**Comment by phoenixwong** [comment]
Sorry for the long wait. Please give the latest release [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0) a try. [#66]

**Comment by morgan-schwertfeger** [comment]
Hi - thanks very much, will do.
Morgan.

Sent from my iPad

On 7 Aug 2019, at 2:34 pm, Phoenix Wong <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry for the long wait. Please give the latest release v0.2.0<https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0> a try. [#66<https://github.com/phoenixwong/vue2-timepicker/pull/66>]
